In [2]:
import numpy as np

A=np.matrix([[0,1],[2,1],[1,2]])
print(A)

[[0 1]
 [2 1]
 [1 2]]


In [4]:
matrix_norm=np.linalg.norm(A,2)
print(matrix_norm)

3.087252641775414


In [54]:
# get x and y where AX=sigma_1*y
U, S, VT = np.linalg.svd(A)
x = VT[0]
print(x)
ysig=np.dot(A,np.transpose(x))
strech=np.linalg.norm(ysig)
print(strech)
print(ysig)
y = ysig/np.linalg.norm(ysig)
print(y)

[[-0.66180256 -0.74967818]]
3.0872526417754145
[[-0.74967818]
 [-2.0732833 ]
 [-2.16115891]]
[[-0.2428302 ]
 [-0.67156256]
 [-0.70002658]]


In [76]:
def gram_schmidt(vectors):
    basis = []
    for v in vectors:
        w=v
        for b in basis:
            w-=np.dot(v,b)*b
        if (np.abs(w) > 1e-10).any():  
            basis.append(w/np.linalg.norm(w))
    return np.array(basis)

In [77]:
yList=[a[0,0] for a in y]
e1=[1,0,0]
e2=[0,1,0]

In [78]:
vectorsy=np.array([yList,e1,e2])
Z1T=gram_schmidt(vectorsy)
Z1 = np.transpose(Z1T)
print(Z1T)
print(Z1)

[[-0.2428302  -0.67156256 -0.70002658]
 [ 0.97006881 -0.16810732 -0.17523251]
 [ 0.          0.7216257  -0.69228343]]
[[-0.2428302   0.97006881  0.        ]
 [-0.67156256 -0.16810732  0.7216257 ]
 [-0.70002658 -0.17523251 -0.69228343]]


In [79]:
# same for x and W
xList=[a[0,0] for a in np.transpose(x)]
e1=[1,0]
vectorsx=np.array([xList,e1])
print(vectorsx)

[[-0.66180256 -0.74967818]
 [ 1.          0.        ]]


In [80]:
W1T=gram_schmidt(vectorsx)
W1=np.transpose(W1T)
print(W1T)
print(W1)

[[-0.66180256 -0.74967818]
 [ 0.74967818 -0.66180256]]
[[-0.66180256  0.74967818]
 [-0.74967818 -0.66180256]]


In [84]:
A1=np.round(Z1T@A@W1,4)
print(A1)

[[ 3.0873  0.    ]
 [ 0.     -0.6822]
 [ 0.      1.0017]]


In [88]:
B=np.transpose(np.matrix(A1[1:,1]))
print(B)

[[-0.6822]
 [ 1.0017]]


## new iteration with B

In [109]:
xB=[1]
yBsig=np.dot(B,xB)
print(yBsig)
strech2=np.linalg.norm(yBsig)
yB=yBsig/np.linalg.norm(yBsig)
print(yB)

[[-0.6822  1.0017]]
[[-0.56289893  0.82652574]]


In [93]:
yBList=[yB[0,0], yB[0,1]]
print(yBList)
e1=[1,0]

[-0.5628989299192757, 0.8265257374672215]


In [94]:
vectorsyB=np.array([yBList,e1])
Z2T=gram_schmidt(vectorsyB)
Z2=np.transpose(Z2T)
print(Z2T)
print(Z2)

[[-0.56289893  0.82652574]
 [ 0.82652574  0.56289893]]
[[-0.56289893  0.82652574]
 [ 0.82652574  0.56289893]]


In [96]:
W2T=[[1]]
W2 = [[1]]

In [106]:
Z2ext=np.concatenate([[[0,0]],Z2],0)
print(Z2ext)
Z2ext=np.concatenate([[[1],[0],[0]],Z2ext],1)
print(Z2ext)

[[ 0.          0.        ]
 [-0.56289893  0.82652574]
 [ 0.82652574  0.56289893]]
[[ 1.          0.          0.        ]
 [ 0.         -0.56289893  0.82652574]
 [ 0.          0.82652574  0.56289893]]


In [111]:
W2ext=np.concatenate([[[0]],W2],0)
print(W2ext)
W2ext=np.concatenate([[[1],[0]],W2ext],1)
print(W2ext)
W2extT=np.transpose(W2ext)

[[0]
 [1]]
[[1 0]
 [0 1]]


In [110]:
sigmaext=np.array([[strech,0],[0,strech2],[0,0]])
print(sigmaext)

[[3.08725264 0.        ]
 [0.         1.21194048]
 [0.         0.        ]]


In [113]:
np.round(Z1@Z2ext@sigmaext@W2extT@W1T,4)

array([[0., 1.],
       [2., 1.],
       [1., 2.]])

In [114]:
U=Z1@Z2ext
print(np.round(U,4))
VT=W2extT@W1T
print(np.round(np.transpose(VT),4))

[[-0.2428 -0.5461  0.8018]
 [-0.6716  0.6911  0.2673]
 [-0.7    -0.4736 -0.5345]]
[[-0.6618  0.7497]
 [-0.7497 -0.6618]]


In [118]:
np.linalg.matrix_rank(np.transpose(A)@A)
AT=np.transpose(A)
I2in3=np.array([[1,0,0],[0,1,0],[0,0,0]])

In [120]:
print(AT)
AT@I2in3

[[0 2 1]
 [1 1 2]]


matrix([[0, 2, 0],
        [1, 1, 0]])