In [7]:
import numpy as np

def unfold1(A):
    return np.hstack([A[:,j,:] for j in range(len(A[0]))])

def unfold2(A):
    return (np.hstack([A[:,:,j].transpose() for j in range(len(A[0,0]))]))

def unfold3(A):
    return (np.hstack([A[j,:,:].transpose() for j in range(len(A))]))

def tmul1(A,U):
    [l,m,n] = A.shape
    result = np.zeros([l,m,n])
    for j in range(l):
        for i2 in range(m):
            for i3 in range(n):
                for k in range(l):
                    result[j,i2,i3] += U[j,k]*A[k,i2,i3]
    return result
 
def tmul2(A,U):
    [l,m,n] = A.shape
    result = np.zeros([l,m,n])
    for i1 in range(l):
        for j in range(m):
            for i3 in range(n):
                for k in range(m):
                    result[i1,j,i3] += U[j,k]*A[i1,k,i3]
    return result

def tmul3(A,U):
    [l,m,n] = A.shape
    result = np.zeros([l,m,n])
    for i1 in range(l):
        for i2 in range(m):
            for j in range(n):
                for k in range(n):
                    result[i1,i2,j] += U[j,k]*A[i1,i2,k]
    return result
 
A = np.zeros([3,3,3])
A[:,:,0] = np.array([[1,2,3],[4,5,6],[7,8,9]])
A[:,:,1] = A[:,:,0]+10
A[:,:,2] = A[:,:,0]+20

U = np.array([[100,0,0],[0,1,0],[0,0,1]])
P = np.array([[0,1,0],[1,0,0],[0,0,1]])
 
tmul1(A,U)




array([[[ 100., 1100., 2100.],
        [ 200., 1200., 2200.],
        [ 300., 1300., 2300.]],

       [[   4.,   14.,   24.],
        [   5.,   15.,   25.],
        [   6.,   16.,   26.]],

       [[   7.,   17.,   27.],
        [   8.,   18.,   28.],
        [   9.,   19.,   29.]]])

In [17]:
A=np.zeros([5,3,2])
A[:,:,0] = np.array([[1,2,0],[0,1,1],[1,1,0],[0,0,4],[2,0,2]])
A[:,:,1] = np.array([[0,0,1],[0,0,1],[4,0,0],[0,2,0],[0,0,2]])
unfold1(A)
#calc frobenius norm of A
frobenius_norm = np.linalg.norm(A)
print(frobenius_norm)

7.681145747868608


In [26]:
import tensorly as tl
from tensorly.decomposition import parafac

# Perform Higher Order Singular Value Decomposition (HOSVD)
HOSVD = tl.decomposition.tucker(A, rank=None)
core = HOSVD.core
# core: core tensor
# factors: list of factor matrices

# Print the core tensor
print("Core Tensor:")
print(core)
print(core.shape)

#calc frobenius norm
frobenius_norm_core = np.linalg.norm(core)
print(frobenius_norm_core)

print("mode1")
# mode 1 singular value
for i in range(5):
    S1= core[i,:,:]
    s1 = np.linalg.norm(S1)
    print(s1)
# mode 3 singular value
print("mode3")
for i in range(2):
    S3= core[:,:,i]
    s3 = np.linalg.norm(S3)
    print(s3)



Core Tensor:
[[[ 4.82389273 -1.02825112]
  [-0.63443298  0.67017853]
  [ 1.07024011  0.82713589]]

 [[ 0.93778856  1.83411894]
  [ 3.1337146   1.19051392]
  [ 0.06659143 -1.83627666]]

 [[ 0.61601439  0.52531936]
  [ 0.02535461 -2.78814987]
  [ 0.19848196 -0.91787394]]

 [[ 0.36500961  0.1553939 ]
  [ 0.22340773 -0.18523331]
  [-1.66663787  0.54234865]]

 [[ 0.07378512  0.33624092]
  [-0.47755501  0.17477805]
  [-0.14441377 -0.33337103]]]
(5, 3, 2)
7.681145747868604
mode1
5.196965803346327
4.342496588518658
3.051515095148708
1.820281711217488
0.7135123919311707
mode3
6.257523788042195
4.45459269092989


/home/bela/git/matrixmethods_dataanalysis/.venv/lib/python3.10/site-packages/tensorly/decomposition/_tucker.py:156: Warning: No value given for 'rank'. The decomposition will preserve the original size.
  warnings.warn(message, Warning)
