In [5]:
import numpy as np

In [6]:
def householderMatrix(vector):
    vector = np.array(vector)
    n = len(vector)
    I = np.eye(n)
    v = vector / np.linalg.norm(vector)
    return I - 2 * np.outer(v, v)

In [7]:
A=np.matrix([[1,0,2],[1,1,0],[2,1,1],[0,1,2],[1,2,1]])

In [8]:
col1=A[:,0]

In [19]:
householderVector1 = col1 + np.linalg.norm(col1) * np.matrix(np.eye(5,1))[:,0] *np.sign(col1[0,0])
print(householderVector1)

[[3.64575131]
 [1.        ]
 [2.        ]
 [0.        ]
 [1.        ]]


In [21]:
Hmatrix1= householderMatrix(householderVector1)
print(Hmatrix1)

[[-0.37796447 -0.37796447 -0.75592895  0.         -0.37796447]
 [-0.37796447  0.89632741 -0.20734518  0.         -0.10367259]
 [-0.75592895 -0.20734518  0.58530965  0.         -0.20734518]
 [ 0.          0.          0.          1.          0.        ]
 [-0.37796447 -0.10367259 -0.20734518  0.          0.89632741]]


In [25]:
A1=Hmatrix1@A
print(A1)

[[-2.64575131e+00 -1.88982237e+00 -1.88982237e+00]
 [ 1.11022302e-16  4.81637061e-01 -1.06694671e+00]
 [ 2.22044605e-16 -3.67258783e-02 -1.13389342e+00]
 [ 0.00000000e+00  1.00000000e+00  2.00000000e+00]
 [ 1.11022302e-16  1.48163706e+00 -6.69467095e-02]]


In [27]:
col2=A1[1:,1]
print(col2)

[[ 0.48163706]
 [-0.03672588]
 [ 1.        ]
 [ 1.48163706]]


In [28]:
householderVector2 = col2 + np.linalg.norm(col2) * np.matrix(np.eye(4,1))[:,0] *np.sign(col2[0,0])
print(householderVector2)

[[ 2.33327726]
 [-0.03672588]
 [ 1.        ]
 [ 1.48163706]]


In [30]:
householderVector2 = np.concatenate((np.zeros((1,1)),householderVector2),axis=0)
print(householderVector2)

[[ 0.        ]
 [ 2.33327726]
 [-0.03672588]
 [ 1.        ]
 [ 1.48163706]]


In [31]:
Hmatrix2= householderMatrix(householderVector2)

In [33]:
A2=Hmatrix2 @ A1
print(A2)

[[-2.64575131e+00 -1.88982237e+00 -1.88982237e+00]
 [-1.13311663e-16 -1.85164020e+00 -7.71516750e-01]
 [ 2.25575631e-16 -5.94769025e-18 -1.13854350e+00]
 [-9.61454385e-17  1.35641556e-16  2.12661588e+00]
 [-3.14303425e-17  8.29732565e-17  1.20652075e-01]]


In [39]:
col3=A2[2:,2]
print(col3)

[[-1.1385435 ]
 [ 2.12661588]
 [ 0.12065207]]


In [41]:
householderVector3 = col3 + np.linalg.norm(col3) * np.matrix(np.eye(3,1))[:,0] *np.sign(col3[0,0])
print(householderVector3)

[[-3.55377296]
 [ 2.12661588]
 [ 0.12065207]]


In [42]:
householderVector3 = np.concatenate((np.zeros((2,1)),householderVector3),axis=0)
print(householderVector3)

[[ 0.        ]
 [ 0.        ]
 [-3.55377296]
 [ 2.12661588]
 [ 0.12065207]]


In [43]:
Hmatrix3= householderMatrix(householderVector3)

In [46]:
A3=Hmatrix3 @A2
print(A3)

[[-2.64575131e+00 -1.88982237e+00 -1.88982237e+00]
 [-1.13311663e-16 -1.85164020e+00 -7.71516750e-01]
 [-1.92563162e-16  1.26381402e-16  2.41522946e+00]
 [ 1.54073303e-16  5.64544061e-17  6.91698860e-17]
 [-1.72343560e-17  7.84806286e-17 -2.08897245e-18]]


In [47]:
print(np.round(A3,2))

[[-2.65 -1.89 -1.89]
 [-0.   -1.85 -0.77]
 [-0.    0.    2.42]
 [ 0.    0.    0.  ]
 [-0.    0.   -0.  ]]
