In [1]:
import numpy as np

In [3]:
A=np.matrix([[1,0,2],[1,1,0],[2,1,1],[0,1,2],[1,2,1]])
print(A)

[[1 0 2]
 [1 1 0]
 [2 1 1]
 [0 1 2]
 [1 2 1]]


In [4]:
np.linalg.svd(A)

SVDResult(U=matrix([[-4.33248985e-01, -5.32657384e-01, -5.00000000e-01,
         -5.24527356e-01,  5.86726644e-02],
        [-2.50681348e-01,  4.72094427e-01,  1.97890423e-16,
         -3.57991507e-01, -7.65589835e-01],
        [-5.29976177e-01,  3.23789341e-01, -5.00000000e-01,
          5.96125657e-01,  9.44453026e-02],
        [-4.33248985e-01, -5.32657384e-01,  5.00000000e-01,
          3.81330753e-01, -3.64908598e-01],
        [-5.29976177e-01,  3.23789341e-01,  5.00000000e-01,
         -3.09732452e-01,  5.18026565e-01]]), S=array([4.25927558, 1.96432471, 1.41421356]), Vh=matrix([[-5.33860471e-01, -5.33860471e-01, -6.55733174e-01],
        [ 4.63673374e-01,  4.63673374e-01, -7.54992718e-01],
        [-7.07106781e-01,  7.07106781e-01,  1.11022302e-16]]))