In [3]:
import numpy as np

A=np.array([[1,2,3],[4,5,6],[7,8,9],[1,1,1]])

[Q,R] = np.linalg.qr(A)
print(Q,"\n",R)

[[-0.12216944  0.8899956  -0.43500081]
 [-0.48867778  0.30745303  0.79343294]
 [-0.85518611 -0.27508955 -0.35843213]
 [-0.12216944 -0.19418086 -0.22970605]] 
 [[-8.18535277e+00 -9.65138610e+00 -1.11174194e+01]
 [ 0.00000000e+00  9.22359078e-01  1.84471816e+00]
 [ 0.00000000e+00  0.00000000e+00  2.48253415e-16]]


In [ ]:
# normal